In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression


# LinearRegression

In [2]:
df = pd.read_csv('taxi_dataset_with_target.csv')
df.head(10)

id  vendor_id      pickup_datetime  passenger_count  \
0  id2875421          1  2016-03-14 17:24:55       930.399753   
1  id2377394          0  2016-06-12 00:43:35       930.399753   
2  id3858529          1  2016-01-19 11:35:24       930.399753   
3  id3504673          1  2016-04-06 19:32:31       930.399753   
4  id2181028          1  2016-03-26 13:30:55       930.399753   
5  id0801584          1  2016-01-30 22:01:40      1061.355223   
6  id1813257          0  2016-06-17 22:34:59      1053.529749   
7  id1324603          1  2016-05-21 07:54:58       930.399753   
8  id1301050          0  2016-05-27 23:12:23       930.399753   
9  id0012891          1  2016-03-10 21:45:01       930.399753   

   store_and_fwd_flag  trip_duration  distance_km  
0                   0          455.0     1.500479  
1                   0          663.0     1.807119  
2                   0         2124.0     6.392080  
3                   0          429.0     1.487155  
4                   0          435.0     1.189925  
5                   0          443.0     1.100107  
6                   0          341.0     1.327852  
7                   0         1551.0     5.722427  
8                   0          255.0     1.311541  
9                   0         1225.0     5.126939

In [3]:
X = df[['vendor_id', 'passenger_count', 'store_and_fwd_flag', 'distance_km']]
Y = df[['trip_duration']]

In [4]:
model = LinearRegression().fit(X, Y)

In [5]:
print(model.coef_, model.intercept_)

[[198.46313674   0.29631295  56.46912165 115.27353763]] [171.65658146]


# Function LinearRegressionByMatrix

In [ ]:
Теперь реализуйте функцию LinearRegressionByMatrix, которая будет принимать на вход 3 параметра:

Матрицу объект-признак (X), вектор с ответами (Y), булевый параметр fit_intercept, цель которого - добавить константный признак (состоящий из единичек), если True, и ничего не делать, если False.

Функция должна вернуть одномерный np.array объект с оцененными  𝛽1,...,𝛽𝑛,𝛽0 

Реализуйте решение через аналитическое решение в матрицах из лекции и практики:

𝛽∗=(𝑋𝑇⋅𝑋)−1⋅𝑋𝑇⋅𝑌

In [4]:
def LinearRegressionByMatrix(X: np.array, Y: np.array, fit_intercept: bool = True):
    X = np.c_[X, np.ones(X.shape[0])]
    return np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), Y)

In [5]:
X_train = df.drop(['trip_duration', 'pickup_datetime', 'id'], axis = 1).values
Y_train = df['trip_duration'].values

print(X_train)
print(Y_train)

[[  1.         930.39975328   0.           1.50047895]
 [  0.         930.39975328   0.           1.80711941]
 [  1.         930.39975328   0.           6.39208025]
 ...
 [  1.         930.39975328   0.           7.83295239]
 [  0.         930.39975328   0.           1.09378613]
 [  0.         930.39975328   0.           1.13545341]]
[ 455.  663. 2124. ...  764.  373.  198.]


In [6]:
LinearRegressionByMatrix(X_train, Y_train, fit_intercept = True)

array([198.46313674,   0.29631295,  56.46912165, 115.27353763,
       171.65658145])